### ISSUE TITLE
Black ground when mod is enabled

### ISSUE THREAD

**Issue by TheAyes** [Telkine2018/factory_graph#2]
Hello! I'm experiencing a bug I believe. What's happening is this. 

There are black spots all over the place 
![image](https://github.com/Telkine2018/factory_graph/assets/68541335/d322496b-783d-4475-a467-7d205bcd5e18)

The issue resolves once the mod is being disabled.

**Comment by schoos76** [comment]
Having the same issue and the same workaround.

**Comment by schoos76** [comment]
Issue looks fixed in the 1.0.4 on the mod portal
